=== pmacsal2707/XMLRep/act7/editorial/editorial.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="EdicionesAranda">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="InformeRegionalVentas">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Descripcion" type="xs:string" />
              <xs:element name="Region">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Norte">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Trimestres">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="Trimestre1">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="librosVendidos" type="xs:unsignedByte" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="Trimestre2">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="librosVendidos" type="xs:unsignedByte" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="Trimestre3">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="librosVendidos" type="xs:unsignedByte" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="Trimestre4">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="librosVendidos" type="xs:unsignedByte" />
                                    </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Centro">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Trimestres">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="Trimestre1">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="librosVendidos" type="xs:unsignedShort" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="Trimestre2">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="librosVendidos" type="xs:unsignedShort" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="Trimestre3">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="librosVendidos" type="xs:unsignedShort" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="Trimestre4">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="librosVendidos" type="xs:unsignedShort" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Sur">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Trimestres">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="Trimestre1">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="librosVendidos" type="xs:unsignedShort" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="Trimestre2">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="librosVendidos" type="xs:unsignedShort" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="Trimestre3">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="librosVendidos" type="xs:unsignedShort" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="Trimestre4">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="librosVendidos" type="xs:unsignedShort" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="fecha" type="xs:date" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== pmacsal2707/XMLRep/act7/editorial/editorial_X.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<EdicionesAranda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="editorial.xsd">
    <InformeRegionalVentas fecha="2024-01-29">
        <Descripcion>Informe de Ventas Regionales</Descripcion>
        <Region>
            <Norte>
                <Trimestres>
                    <Trimestre1>
                        <librosVendidos>100</librosVendidos>
                    </Trimestre1>
                    <Trimestre2>
                        <librosVendidos>200</librosVendidos>
                    </Trimestre2>
                    <Trimestre3>
                        <librosVendidos>150</librosVendidos>
                    </Trimestre3>
                    <Trimestre4>
                        <librosVendidos>250</librosVendidos>
                    </Trimestre4>
                </Trimestres>
            </Norte>
            <Centro>
                <Trimestres>
                    <Trimestre1>
                        <librosVendidos>300</librosVendidos>
                    </Trimestre1>
                    <Trimestre2>
                        <librosVendidos>400</librosVendidos>
                    </Trimestre2>
                    <Trimestre3>
                        <librosVendidos>350</librosVendidos>
                    </Trimestre3>
                    <Trimestre4>
                        <librosVendidos>450</librosVendidos>
                    </Trimestre4>
                </Trimestres>
            </Centro>
            <Sur>
                <Trimestres>
                    <Trimestre1>
                        <librosVendidos>500</librosVendidos>
                    </Trimestre1>
                    <Trimestre2>
                        <librosVendidos>600</librosVendidos>
                    </Trimestre2>
                    <Trimestre3>
                        <librosVendidos>550</librosVendidos>
                    </Trimestre3>
                    <Trimestre4>
                        <librosVendidos>650</librosVendidos>
                    </Trimestre4>
                </Trimestres>
            </Sur>
        </Region>
    </InformeRegionalVentas>
</EdicionesAranda>
