=== pmacsal2707/XMLRep/act1/ejRealbiblioteca/videojuegos.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
version="0.1" xml:lang="es">
  
  <xs:element name="videojuegos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="videojuego" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titulo" type="xs:string"/>
              <xs:element name="desarrollador" type="xs:string"/>
              <xs:element name="lanzamiento" type="xs:string"/>
              <xs:element name="genero" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== pmacsal2707/XMLRep/act1/ejRealbiblioteca/videojuegos_X.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<videojuegos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="videojuegos.xsd">
    <videojuego>
      <titulo>The Legend of Zelda: Breath of the Wild</titulo>
      <desarrollador>Nintendo</desarrollador>
      <lanzamiento>3 de marzo de 2017</lanzamiento>
      <genero>Aventura</genero>
    </videojuego>
    <videojuego>
      <titulo>Super Mario Bros.</titulo>
      <desarrollador>Nintendo</desarrollador>
      <lanzamiento>13 de septiembre de 1985</lanzamiento>
      <genero>Plataformas</genero>
    </videojuego>
    <videojuego>
      <titulo>The Witcher 3: Wild Hunt</titulo>
      <desarrollador>CD Projekt</desarrollador>
      <lanzamiento>19 de mayo de 2015</lanzamiento>
      <genero>RPG de acción</genero>
    </videojuego>
    <videojuego>
      <titulo>Grand Theft Auto V</titulo>
      <desarrollador>Rockstar North</desarrollador>
      <lanzamiento>17 de septiembre de 2013</lanzamiento>
      <genero>Acción y aventura</genero>
    </videojuego>
    <videojuego>
      <titulo>Skyrim</titulo>
      <desarrollador>Bethesda Game Studios</desarrollador>
      <lanzamiento>11 de noviembre de 2011</lanzamiento>
      <genero>RPG de acción</genero>
    </videojuego>
    <videojuego>
      <titulo>Dark Souls</titulo>
      <desarrollador>FromSoftware</desarrollador>
      <lanzamiento>22 de septiembre de 2011</lanzamiento>
      <genero>Acción y RPG</genero>
    </videojuego>
    <videojuego>
      <titulo>The Elder Scrolls IV: Oblivion</titulo>
      <desarrollador>Bethesda Game Studios</desarrollador>
      <lanzamiento>20 de marzo de 2006</lanzamiento>
      <genero>RPG de acción</genero>
    </videojuego>
    <videojuego>
      <titulo>Red Dead Redemption 2</titulo>
      <desarrollador>Rockstar Studios</desarrollador>
      <lanzamiento>26 de octubre de 2018</lanzamiento>
      <genero>Aventura de acción</genero>
    </videojuego>
    <videojuego>
      <titulo>Portal 2</titulo>
      <desarrollador>Valve</desarrollador>
      <lanzamiento>18 de abril de 2011</lanzamiento>
      <genero>Puzzle, Plataformas</genero>
    </videojuego>
    <videojuego>
      <titulo>Half-Life 2</titulo>
      <desarrollador>Valve</desarrollador>
      <lanzamiento>16 de noviembre de 2004</lanzamiento>
      <genero>Shooter en primera persona</genero>
    </videojuego>
  </videojuegos>
