=== pmacsal2707/XMLRep/act7/ejRealeditorial/editorial.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="informeVentasAutomoviles">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="informeRegionalAutomoviles">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Descripcion" type="xs:string" />
              <xs:element name="Ubicacion">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="EstadosUnidos">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Periodos">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="Primavera">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="automovilesVendidos" type="xs:unsignedByte" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="Verano">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="automovilesVendidos" type="xs:unsignedByte" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="Otoño">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="automovilesVendidos" type="xs:unsignedShort" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="Invierno">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="automovilesVendidos" type="xs:unsignedByte" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Canada">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Periodos">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="Primavera">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="automovilesVendidos" type="xs:unsignedShort" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="Verano">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="automovilesVendidos" type="xs:unsignedByte" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="Otoño">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="automovilesVendidos" type="xs:unsignedByte" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="Invierno">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="automovilesVendidos" type="xs:unsignedShort" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Mexico">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Periodos">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="Primavera">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="automovilesVendidos" type="xs:unsignedShort" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="Verano">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="automovilesVendidos" type="xs:unsignedByte" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="Otoño">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="automovilesVendidos" type="xs:unsignedByte" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="Invierno">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="automovilesVendidos" type="xs:unsignedByte" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="fecha" type="xs:date" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== pmacsal2707/XMLRep/act7/ejRealeditorial/editorial_X.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<informeVentasAutomoviles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="editorial.xsd">
    <informeRegionalAutomoviles fecha="2024-02-01">
        <Descripcion>Reporte de ventas de automóviles por región y temporada</Descripcion>
        <Ubicacion>
            <EstadosUnidos>
                <Periodos>
                    <Primavera>
                        <automovilesVendidos>100</automovilesVendidos>
                    </Primavera>
                    <Verano>
                        <automovilesVendidos>250</automovilesVendidos>
                    </Verano>
                    <Otoño>
                        <automovilesVendidos>698</automovilesVendidos>
                    </Otoño>
                    <Invierno>
                        <automovilesVendidos>255</automovilesVendidos>
                    </Invierno>
                </Periodos>        
            </EstadosUnidos>
            <Canada>
                <Periodos>
                    <Primavera>
                        <automovilesVendidos>300</automovilesVendidos>
                    </Primavera>
                    <Verano>
                        <automovilesVendidos>100</automovilesVendidos>
                    </Verano>
                    <Otoño>
                        <automovilesVendidos>160</automovilesVendidos>
                    </Otoño>
                    <Invierno>
                        <automovilesVendidos>270</automovilesVendidos>
                    </Invierno>
                </Periodos>
            </Canada>
            <Mexico>
                <Periodos>
                    <Primavera>
                        <automovilesVendidos>500</automovilesVendidos>
                    </Primavera>
                    <Verano>
                        <automovilesVendidos>100</automovilesVendidos>
                    </Verano>
                    <Otoño>
                        <automovilesVendidos>150</automovilesVendidos>
                    </Otoño>
                    <Invierno>
                        <automovilesVendidos>100</automovilesVendidos>
                    </Invierno>
                </Periodos>
            </Mexico>
        </Ubicacion>
    </informeRegionalAutomoviles>
</informeVentasAutomoviles>
